<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class OneHundredSeeder extends Seeder
{
    public function run(): void
    {
        $articles = [
            [
                'title' => 'Orkestrasi Container dengan Docker Compose',
                'slug' => Str::slug('Orkestrasi Container dengan Docker Compose Dasar'),
                'category' => 'DevOps',
                'author' => 'DevOps Engineer',
                'read_time' => 8,
                'excerpt' => 'Menjalankan WordPress dan MySQL dalam 2 container terpisah secara bersamaan hanya dengan 1 file manifest yaml dan 1 perintah terminal.',
                'content' => "<h3>1. Masalah pada Docker Run</h3>\n<p>Jika App Anda butuh Database, menjalankan `docker run` dua kali dengan network link sangatlah merepotkan. <b>Docker Compose</b> mengorkestrasi multi-container secara harmoni dalam 1 grup berkat file `docker-compose.yml`.</p>\n<h3>2. Struktur Manifest YAML</h3>\n<pre><code class=\"language-yaml\">version: '3.8'\nservices:\n  db_mysql:\n    image: mysql:8.0\n    restart: always\n    environment:\n      MYSQL_ROOT_PASSWORD: rahasia_banget\n      MYSQL_DATABASE: wordpress_db\n    volumes:\n      # Menyimpan data DB secara persisten di folder host\n      - ./koleksi_data:/var/lib/mysql\n\n  web_wordpress:\n    depends_on:\n      - db_mysql # Tunggu DB hidup duluan sebelum nyala!\n    image: wordpress:latest\n    ports:\n      - \"8080:80\"\n    environment:\n      WORDPRESS_DB_HOST: db_mysql:3306\n      WORDPRESS_DB_USER: root\n      WORDPRESS_DB_PASSWORD: rahasia_banget\n      WORDPRESS_DB_NAME: wordpress_db</code></pre>\n<h3>3. Nyalakan Mesinnya!</h3>\n<pre><code class=\"language-bash\"># -d artinya Detach (Tinggalkan jalan di Background Console)\ndocker-compose up -d\n\n# Mengecek status kedua container yang hidup sehidup semati ini\ndocker-compose ps</code></pre>",
                'level_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pengenalan Message Broker: RabbitMQ',
                'slug' => Str::slug('Pengenalan Message Broker RabbitMQ Dasar'),
                'category' => 'Cloud',
                'author' => 'Software Architect',
                'read_time' => 7,
                'excerpt' => 'Cara mencegah server Crash atau Timeout saat aplikasi Anda disuruh mengirim 10.000 Email sekaligus. Delegasikan antrian pekerjaan menggunakan RabbitMQ.',
                'content' => "<h3>1. Apa itu Message Broker Server?</h3>\n<p>Saat Anda memencet klik \"Beli\" di Tokopedia, sistem harus: Memotong Saldo, Ngabari Kurir, Mengirim Notifikasi Email, dll. Jika dikerjakan secara runtut (Synchronous), web akan muter loading sangat lama! RabbitMQ adalah server \"Tukang Pos\" penampung antrian perintah asynchronus tersebut.</p>\n<h3>2. Instalasi RabbitMQ Server (Debian)</h3>\n<pre><code class=\"language-bash\">apt install curl gnupg -y\napt install rabbitmq-server -y</code></pre>\n<h3>3. Menghidupkan Plugin GUI Dashboard Web</h3>\n<p>RabbitMQ aslinya hitam putih. Tapi ada GUI bawaan yang mati (Disable). Ayo hidupkan!</p>\n<pre><code class=\"language-bash\">rabbitmq-plugins enable rabbitmq_management\nsystemctl restart rabbitmq-server</code></pre>\n<h3>4. Manajemen Admin</h3>\n<pre><code class=\"language-bash\"># Buat User baru (karena guest tidak bisa akses jarak jauh diluar localhost)\nrabbitmqctl add_user BosRabbit sandiku123\n# Beri gelar Administrator sakti mumpuni\nrabbitmqctl set_user_tags BosRabbit administrator\n# Beri izin rwx akses di seluruh virtual host (/)\nrabbitmqctl set_permissions -p / BosRabbit \".*\" \".*\" \".*\"</code></pre>\n<p>Buka portalnya di Browser Anda: <code>http://IP_SERVER:15672</code> dan log in!</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Redis Caching: Menyimpan Data Super Cepat di RAM',
                'slug' => Str::slug('Redis Caching Menyimpan Data di RAM'),
                'category' => 'Database',
                'author' => 'Database Architect',
                'read_time' => 5,
                'excerpt' => 'SQL (Harddisk) terlalu lambat untuk menampilkan Berita Tranding Hari Ini. Percepat web ratusan kali lipat dengan menaruh cache query di dalam Redis In-Memory Database.',
                'content' => "<h3>1. Paradigma RAM Database (Key-Value)</h3>\n<p>Redis adalah kependekan dari Remote Dictionary Server. Redis TIDAK MENGGUNAKAN Tabel & Kolom. Ia hanya sepasang kunci (Key) dan isi (Value). Data tidak ditulis ke SSD, melainkan DITAHAN di dalam putaran RAM server agar read-nya Instan mili-detik.</p>\n<h3>2. Instalasi</h3>\n<pre><code class=\"language-bash\">apt update\napt install redis-server -y</code></pre>\n<h3>3. Pengamanan Default Bind (Hardening)</h3>\n<p>Redis yang terbuka ke Publik TANPA KATA SANDI adalah makanan empuk Botnet Mining Kripto! Tutup di <code>/etc/redis/redis.conf</code></p>\n<pre><code class=\"language-ini\"># Hanya izinkan aplikasi dari server ini sendiri (PHP/NodeJS) yang berinteraksi dengan API Redis\nbind 127.0.0.1 ::1\n\n# Pasang password (walaupun untuk internal web localhost)\nrequirepass SandiSangatKuat_123</code></pre>\n<h3>4. Operasi Terminal (Redis-CLI)</h3>\n<pre><code class=\"language-bash\">redis-cli\n# Jika pakai sandi\n> AUTH SandiSangatKuat_123\n\n# Memasukkan nilai memori (cache)\n> SET token_login_ari \"XYZ_RAHASIA_KODE\"\n# Mengambilnya kembali\n> GET token_login_ari\n\n# Mensetting Data agar HANCUR DIRINYA SENDIRI setelah 1 Menit (Hitung mundur TTL 60 Detik)\n> SETEX promo_flash_sale 60 \"Diskon Rp 10rb!\"\n> TTL promo_flash_sale</code></pre>",
                'level_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Continuous Deployment Canggih: GitOps dengan ArgoCD',
                'slug' => Str::slug('Continuous Deployment GitOps ArgoCD'),
                'category' => 'DevOps',
                'author' => 'Kubernetes Master',
                'read_time' => 10,
                'excerpt' => 'Masa depan Deployment Kubernetes. Biarkan ArgoCD memelototi Repo Github Anda. Jika GitHub berubah, Cluster k8s akan dipaksa menyesuaikan diri secara agresif (State Sync).',
                'content' => "<h3>1. Transisi CI/CD Menjadi GitOps (Pull vs Push)</h3>\n<p>Pada pipeline jadul (Jenkins/GitLab-CI), Script di GitHub akan 'Mendorong (PUSH)' update ke Server. Di kubernetes <b>GitOps</b>, justru ArgoCD dipasang di DALAM cluster K8S, dia bertindak sbagai 'Anak Buah' yang tiap 3 menit PULL memelototi GitHub Bapaknya. Jika file YAML di github berubah, dia mengubah Server!</p>\n<h3>2. Instalasi ArgoCD Core di Kubernetes</h3>\n<pre><code class=\"language-bash\"># Menciptakan alam namespace spesifik\nkubectl create namespace argocd\n\n# Tembak install raw manifest langsung dari pabrik dev nya\nkubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml</code></pre>\n<h3>3. Eksekusi Login</h3>\n<pre><code class=\"language-bash\"># Forwarding Dashboard GUI ArgoCD agar bisa diakses Laptop\nkubectl port-forward svc/argocd-server -n argocd 8080:443\n\n# Mendapatkan Password Acak bawaan default-nya\nkubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath=\"{.data.password}\" | base64 -d; echo</code></pre>\n<p>Di antarmuka Dashboard Port 8080, silakan klik Add Application. Anda cukup menyebutkan LINK Repo Git anda. ArgoCD akan otomatis mencekam Repo itu menjadi kiblat satu-satunya <b>(Single Source of Truth)</b>.</p>",
                'level_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Monitoring Metrics: Prometheus & Grafana',
                'slug' => Str::slug('Monitoring Metrics Prometheus & Grafana'),
                'category' => 'Cloud',
                'author' => 'System Architect',
                'read_time' => 9,
                'excerpt' => 'Membangun Dashboard TV Keren ala Data Center (NOC). Mengambil data sensor CPU, RAM, Suhu setiap detik memakai Node Exporter dan Prometheus Time-Series DB.',
                'content' => "<h3>1. 3 Komponen Trilogi Observabilitas</h3>\n<p><ul>\n<li><b>Node Exporter:</b> Aplikasi mata-mata 15mb yang ditempel di setiap Server Client (Menjual sensor statistik mereka di port 9100).</li>\n<li><b>Prometheus:</b> Server Induk perampok log (Menghisap masuk data metrik dari ratusan Node Exporter kedalam database Time-Series-nya).</li>\n<li><b>Grafana:</b> Papan tulis lukis visual grafik cantik di layar LED dinding SOC / NOC Anda!</li>\n</ul></p>\n<h3>2. Menanam Bibit Mata-Mata (Node Exporter)</h3>\n<pre><code class=\"language-bash\"># Pasang di Server target korbannya\napt install prometheus-node-exporter -y\nsystemctl enable prometheus-node-exporter\nsystemctl start prometheus-node-exporter</code></pre>\n<h3>3. Meracik Otak Induk Prometheus (Server Utama)</h3>\n<pre><code class=\"language-bash\"># Pasang database induk ini misal di Master VM lain\napt install prometheus -y\n\n# Edit /etc/prometheus/prometheus.yml , beri tahu dia lokasi Targetnya tadi!\nscrape_configs:\n  - job_name: 'Pabrik_Server_Linux'\n    static_configs:\n      - targets: ['localhost:9090', '192.168.10.222:9100']</code></pre>\n<p>Sangat mudah. Anda tinggal Install paket `grafana` (melalui repo deb officialnya), nyalakan webnya di port 3000, login `admin:admin`, tambahkan Data Source -> Prometheus, Import Dashboard ID Sakti `1860`. Beres!</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CI/CD: Automasi Build Pipeline Menggunakan Jenkins Lanjut',
                'slug' => Str::slug('Automasi Build Pipeline Menggunakan Jenkins Lanjut'),
                'category' => 'DevOps',
                'author' => 'DevOps Engineer',
                'read_time' => 8,
                'excerpt' => 'Tinggalkan Upload cPanel. Buat Server Butler (Pelayan Jenkins) yang bertugas mengetes, nge-build npm, lalu melempar file final ke Production Node via Pipeline Jenkins-file.',
                'content' => "<h3>1. Apa Beda Jenkins vs GitLab Runner?</h3>\n<p>Jenkins adalah Bapak moyang CI/CD Agnostik yang tidak terpasung pada Provider Platform manapun (GitLab, Bitbucket, Gitea). Jenkins berdiri kokoh sendiri bagai tank raksasa yang punya ribuan Plugin kompilasi unik.</p>\n<h3>2. Proses Pembangunan Jenkins LTS (Java App)</h3>\n<pre><code class=\"language-bash\"># Instalasi Runtime Java\napt install fontconfig openjdk-17-jre -y\n\n# Mengail repositori sah jenkins GPG\ncurl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \\\n  /usr/share/keyrings/jenkins-keyring.asc > /dev/null\necho deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \\\n  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \\\n  /etc/apt/sources.list.d/jenkins.list > /dev/null\n  \n# Tembak apt installnya!\napt update\napt install jenkins -y</code></pre>\n<h3>3. Mengambil Password Perawan (Pertama Nyala)</h3>\n<pre><code class=\"language-bash\"># Jenkins melindungi instalasi gui web-nya dengan Security PIN acak di balik file log\ncat /var/lib/jenkins/secrets/initialAdminPassword</code></pre>\n<p>Setelah PIN didapat, paste di antarmuka Web GUI port `8080`, klik Next, dan instal \"Suggested Plugins\". Setelah itu Anda dapat membuat sebuah \"Freestyle Project\" Pipeline yang mengeksekusi bash command (misal <code>npm run build && scp -r</code>) setiap kali terjadi Webhook dorongan dari Dev.</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Software Quality Assurance dengan SonarQube',
                'slug' => Str::slug('Software Quality Assurance dengan SonarQube'),
                'category' => 'DevOps',
                'author' => 'QA Automation',
                'read_time' => 7,
                'excerpt' => 'Program Aplikasi Anda jalan dengan sukses, tapi kode di baliknya rongsokan (Spaghetti Code) & rawan Sql-Injection. Analisa mutunya Memakai SonarQube.',
                'content' => "<h3>1. Pengawal Kualitas Static Code Analysis</h3>\n<p>Seorang SysAdmin sering diminta Programer untuk mem-build script PHP mereka. Tapi ternyata script PHP tsb mengandung celah Vulnerability yang menyebabkan Server Web anda ikut bobol. Analisis Static (SAST) menggunakan AI SonarQube bisa memblacklist kode rongsokan tersebut sebelum masuk production!</p>\n<h3>2. Deployment SonarQube Tercepat (Docker)</h3>\n<pre><code class=\"language-bash\"># Sonarqube butuh modifikasi alokasi batasan RAM memory mesin host\nsysctl -w vm.max_map_count=262144\n\n# Eksekusi instan mesin pintar analiser java ini (Pastikan RAM Kamu > 4 GB)\ndocker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest</code></pre>\n<h3>3. Menjalankan Pemindaian (Sonar Scanner) Pada Kode</h3>\n<p>Anggap Anda mendownload repository project `laravel_toko_online`.</p>\n<pre><code class=\"language-bash\"># Dari dalam folder project, jalankan agen CLI scanner milik sonarcube menembak Port 9000 wadah sentral Sonar diatas\n# -D=Definisikan bahwa kunci token loginnya adalah sqa_xxxxxxxx\nsonar-scanner \\\n  -Dsonar.projectKey=TokoOnlineProject \\\n  -Dsonar.sources=. \\\n  -Dsonar.host.url=http://localhost:9000 \\\n  -Dsonar.login=sqp_3x4mpL353CR3Tt0k3N</code></pre>\n<p>Tunggu Loadingnya, dan Web Port 9000 akan menampilkan Grade (B/C/A) dan menunjuk Baris Kode file Line Ke Berapa yang harus di refactor/diperbaiki programer perusahaan Anda.</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Iptables Firewall Lanjut: Source NAT (SNAT) Static',
                'slug' => Str::slug('Iptables Firewall Lanjut Source NAT SNAT Static'),
                'category' => 'Security',
                'author' => 'Network Security Specialist',
                'read_time' => 6,
                'excerpt' => 'Jika Masquerade Mikrotik mengubah IP otomatis secara buta, SNAT (Source NAT) Iptables Linux digunakan untuk menentukan pemisahan IP Publik secara spesifik!',
                'content' => "<h3>1. Bedanya Masquerade vs SNAT di Iptables Linux</h3>\n<p>Keduanya sama-sama membagi akses internet (LAN -> Internet). Namun, Masquerade sangat membebani CPU karena selalu membaca tabel antarmuka dinamis pada IP Dinamis Indihome. SNAT adalah versi ringan/hardcoded. Cocok dipakai kalau IP Publik Pintu Keluar Server Kamu itu STATIS.</p>\n<h3>2. Konfigurasi SNAT di /etc/rc.local</h3>\n<p>Misalkan Server Router Debian kita memiliki Eth0 (Nancep Ke Internet ber IP Statis \"202.12.1.9\") dan Eth1 (Kabel ke Switch Anak Lab Lokal \"10.10.10.0/24\").</p>\n<pre><code class=\"language-bash\"># 1. Pastikan fitur jembatan penyebrangan antara 2 Colokan Ethernet Linux Diaktifkan\necho 1 > /proc/sys/net/ipv4/ip_forward\n\n# 2. Syntax Sakti SNAT Iptables\n# (-t nat = Tabel translasi)\n# (-s 10.x.x.x = Jika IP Asalnya dari anak lab)\n# (-o eth0 = Dan paket tersebut mau memaksakan diri keluar lewat gerbang Eth0)\n# (-j SNAT --to = Merampas paket IP privatenya dan menempelkan stiker IP Publik 202... secara Statik di kulitnya!)\niptables -t nat -A POSTROUTING -s 10.10.10.0/24 -o eth0 -j SNAT --to-source 202.12.1.9</code></pre>\n<p>Server Linux anda sekarang telah menjelma menjadi Router Warnet ala Mikrotik kelas bawah yang sangat cepat memproses tabel networknya!</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Iptables Firewall Lanjut: Destination NAT (Port Forwarding)',
                'slug' => Str::slug('Iptables Firewall Lanjut Destination NAT Port Forwarding'),
                'category' => 'Security',
                'author' => 'Firewall Administrator',
                'read_time' => 5,
                'excerpt' => 'Cara Menyembunyikan Web Server Fisik (Ber-IP Intranet Lokal) ke Belakang Router Linux Ber-IP Publik menggunakan Iptables DNAT Layer 4.',
                'content' => "<h3>1. Kasus Web di Ruang Belakang</h3>\n<p>Server Web Asli Apache <code>10.10.10.25</code> tersimpan di dalam Lemari tertutup tanpa ada IP Publik. Sang Router Gateway <code>(Memiliki IP Publik 202.12.1.9)</code> maju bertindak sebagai tumbal pertahanan / Calo Port Forwarding.</p>\n<h3>2. Eksekusi Pembelokan (Pre-Routing Port-Tricking)</h3>\n<pre><code class=\"language-bash\"># Masih di Server Firewall Gateway, eksekusi pembuangan port trafik\n# -p tcp --dport 80 = Jika ada orang luar internet minta buka ke pelabuhan 80 (Si Gateway Asli)\n# -j DNAT --to = Secara diam-diam (Under-The-Hood) lempar jauh-jauh request orang tersebut masuk tembus ke belakang menuju IP 10.10.10.25 Port 80 asli!\n\niptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 10.10.10.25:80</code></pre>\n<h3>3. Menyimpan Hasil Rules Keadaan Restart</h3>\n<p>Rules iptables akan ghaib/hilang setelah Server direstart. Install paket sakti iptables-persistent.</p>\n<pre><code class=\"language-bash\">apt install iptables-persistent -y\n# Jawab YES pada pertanyaan save current IPv4 rules (Tersimpan otomatis di /etc/iptables/rules.v4)</code></pre>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Membangun Storage Area Network (SAN) Lanjut: iSCSI Target',
                'slug' => Str::slug('Membangun Storage Area Network iSCSI Target'),
                'category' => 'Debian Server',
                'author' => 'Storage Administrator',
                'read_time' => 8,
                'excerpt' => 'NFS hanya menshare file berupa folder. Tapi iSCSI (Target) men-share Harddisk Fiktif Mentahan / Blok Disk utuh melalui kebalik Kabel IP!',
                'content' => "<h3>1. Block-Level (iSCSI) vs File-Level (NFS/Samba)</h3>\n<p>Saat Anda me-Mount fitur iSCSI di Windows Intranet, File System Windows Disk Management (Partisi) akan TERTIPU dan membacanya sebagai Partisi Harddisk Kosong Belum Terformat seakan-akan harddisk tersebut baru tertancap Fisik di Motherboard. Padahal Disk tersebut adanya Jarak Jauh di Datacenter!</p>\n<h3>2. Instalasi LIO (Linux-IO) Target Induk Pemancar</h3>\n<pre><code class=\"language-bash\">apt install targetcli-fb -y\n\n# Membuka terminal interaktif shell milik iscsi setup\ntargetcli\n\n# Langkah A (Membuat Blok Kosong Belakang Layar sejaran 5 Giga)\n/> backstores/fileio create disk_mentah01 /var/lib/iscsi_disks/disk01.img 5G\n\n# Langkah B (Membuat Topeng Pemancar / IQN Standar Format)\n/> iscsi/ create iqn.2026-10.net.perusahaan:nas01\n\n# Langkah C (Mengawinkan File Backstore tadi kedalam Lubang Transmisi LUN 0 pemancar port 3260)\n/> iscsi/iqn.2026-10.net.perusahaan:nas01/tpg1/luns create /backstores/fileio/disk_mentah01\n\n# Langkah D (Pengamanan ACL, Siapa IP yg boleh gigit koneksinya?)\n/> iscsi/iqn.2026-10.net.perusahaan:nas01/tpg1/acls create iqn.1991-05.com.microsoft:windows-client11\n\n# Keluar dan Save!\n/> exit</code></pre>\n<p>Buka Aplikasi <b>iSCSI Initiator</b> di Laptop Windows, bidik IP Linux Debian anda. Tiba-tiba di MyComputer minta Format Partisi Disk D: Ext/NTFS baru sebesar 5GB! Magis!</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Membangun Google Drive Sendiri (Self-Hosted Cloud) via Nextcloud',
                'slug' => Str::slug('Membangun Self Hosted Cloud Nextcloud'),
                'category' => 'Debian Server',
                'author' => 'Cloud Enthusiast',
                'read_time' => 7,
                'excerpt' => 'Bayar Langganan GDrive perbulan mahal? Beli NAS Disk 4TB dan bangun portal penyimpanan Cloud Pindah Kantor Open Source Nextcloud.',
                'content' => "<h3>1. Prerequisite Mutlak LAMP Stack</h3>\n<p>Nextcloud tak lebih dari sebuah software raksasa berbasis PHP. Anda WAJIB punya MariaDB dan mod_php/php-fpm terbaru (PHP 8.2 Disarankan beserta module-module zip, xml, curl, gd).</p>\n<h3>2. Pengunduhan Core dan Hak Akses</h3>\n<pre><code class=\"language-bash\">cd /var/www\n# Unduh gulungan code berekstensi bebas virus (.tar.bz2)\nwget https://download.nextcloud.com/server/releases/nextcloud-27.1.3.tar.bz2\n\n# Ekstrak bungkusan ke folder /var/www/nextcloud\ntar -xjf nextcloud-*.tar.bz2\n\n# Nextcloud butuh Izin Membaca/Menulis Folder Data, karena ia akan meletakkan ratusan file PDF/Foto bawwannya disitu.\nchown -R www-data:www-data /var/www/nextcloud/</code></pre>\n<h3>3. Tuning Modul Database dan Instalasi Setup Web</h3>\n<p>Siapkan database MySql dengan nama `db_cloud` beserta User Privilege-nya layaknya anda menginstall Laravel/WordPress as usual.</p>\n<p>Arahkan VirtualHost Apache (`DocumentRoot`) ke direktori nextcloud anda. Akses di Browser dan Anda disambut Formulir sakti. Silakan isikan kolom SQL nya! Selamat Anda punya Sinkronisasi Foto HP seperti Google Photos, tapi Private!</p>",
                'level_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Migrasi ke VPN Modern: Setup WireGuard Tunnel (Ultra-Fast)',
                'slug' => Str::slug('Setup WireGuard Tunnel VPN Cepat'),
                'category' => 'Security',
                'author' => 'Network Security Specialist',
                'read_time' => 6,
                'excerpt' => 'Lupakan OpenVPN yang lambat dan berat. Gunakan Wireguard, protokol VPN generasi ke-3 langsung hidup di level Kernel Linux dengan baris kode tipis (Hanya 4000 Baris).',
                'content' => "<h3>1. Kenapa Wireguard Super Sakti?</h3>\n<p>WireGuard TIDAK MENAHAN Sesi Koneksi yang terputus spt OpenVPN (Reconnect/Handshake lelet). WireGuard itu mirip UDP Stateless (lempar lari) namun ter-enkripsi Cryptokey canggih bawaan kernel. Ping (Latency) dari WireGuard hanya beda 1-3 ms dari koneksi Telanjang!</p>\n<h3>2. Proses Inti Debian Setup</h3>\n<pre><code class=\"language-bash\">apt install wireguard -y\n\n# Membuat Key Kunci Privat dan Public untuk SERVER di dalam folder yg aman\ncd /etc/wireguard/\numask 077\nwg genkey | tee server_private.key | wg pubkey > server_public.key\n\n# Lakukan hal yg sama untuk Client!\nwg genkey | tee laptop_private.key | wg pubkey > laptop_public.key</code></pre>\n<h3>3. Menulis File Interface Kustom/Sangar (wg0.conf)</h3>\n<pre><code class=\"language-ini\">nano /etc/wireguard/wg0.conf\n\n[Interface]\n# WireGuard akan meng-Claim IP virtual dirinya sebagai 10.0.0.1 (Gateway bayangan)\nAddress = 10.0.0.1/24\nListenPort = 51820 # Port bukaannya bebas (Standar UDP WG)\nPrivateKey = <ISI_DENGAN_TULISAN_SERVER_PRIVATE_KEY_DIDALAM_FASE_2_TADI>\n\n[Peer]\n# Ini adalah profil Laptop Pelanggan/Karyawan yg diizinkan nembak\nPublicKey = <ISI_DENGAN_TULISAN_LAPTOP_PUBLIC_KEY>\n# Diingatkan, VPN IP yg berhak ia sewa cuma .2\nAllowedIPs = 10.0.0.2/32</code></pre>\n<h3>4. Tancap Gas Mode Interface Systemd</h3>\n<pre><code class=\"language-bash\"># Paksa hidup interface (wg0) yg barusan kita ketik.\nsystemctl enable --now wg-quick@wg0</code></pre>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Instalasi Java Tomcat Web Server Deployment Lanjut',
                'slug' => Str::slug('Instalasi Java Tomcat Web Server Deployment'),
                'category' => 'Debian Server',
                'author' => 'Linux System Admin',
                'read_time' => 7,
                'excerpt' => 'Nginx dan Apache tidak bisa mengeksekusi script program JSP (Java Server Pages / Spring Boot). Anda butuh wadah Servlet Kontainer mandiri: Tomcat Engine!',
                'content' => "<h3>1. Penyiapan Spesifikasi Java Runtime Env (JRE)</h3>\n<pre><code class=\"language-bash\">apt update\n# Seluruh Aplikasi korporat dan Perbankan memakai engine Java! Install dulu!\napt install default-jdk -y</code></pre>\n<h3>2. Tambahkan User Pengurung Tomcat (Hardening)</h3>\n<p>Penting! Tomcat berjalan sebagai web server paralel di port 8080. Jangan jalankan via Root.</p>\n<pre><code class=\"language-bash\"># Menambahkan user terkurung (Non-login shell via falsenya)\nuseradd -m -U -d /opt/tomcat -s /bin/false tomcat</code></pre>\n<h3>3. Unduh Distribusi Binari Matang</h3>\n<p>Ke folder opt, wget tar.gz tomcat versi ke 9 atau 10. Extrak seluruh file dan buang di dalam folder instalasi milik user tomcat tadi <code>/opt/tomcat</code>.</p>\n<pre><code class=\"language-bash\"># Jangan lupa! file .sh atau .bat skrip penggerak di dalem bin/, harus diexecutable \nchmod +x /opt/tomcat/bin/*.sh \n# Kuasan pemilikan ke user tomcat tsb\nchown -R tomcat: /opt/tomcat</code></pre>\n<h3>4. Systemd Tweak (Integrasi Control Sederhana)</h3>\n<p>Sama seperti tutor pembuatan Daemon Service sebelumnya. Buatlah script <code>tomcat.service</code> dan tembak jalurnya ke script <code>ExecStart=/opt/tomcat/bin/startup.sh</code>.</p>\n<p>Buka <code>http://IP:8080/</code> dan anda akan disambut Muka Harimau Kuning. Selamat mendeploy file <b>.war</b> (Kumpulan script program kompilasi) anda di GUI Manager tomcat tsb!</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pengenalan DevOps: Lingkungan Vagrant Box Local',
                'slug' => Str::slug('Pengenalan Vagrant Box Local DevOps'),
                'category' => 'DevOps',
                'author' => 'DevOps Trainee',
                'read_time' => 5,
                'excerpt' => 'Ribet mengulangi instalasi manual dan instal OS Debian berkali-kali di VirtualBox nge-lag? Otomatiskan dengan instruksi teks Vagrantfile yang ringan.',
                'content' => "<h3>1. Apa itu Vagrant oleh HashiCorp?</h3>\n<p>Programmer Mac/Windows sering bertengkar \"Di laptopku program aplikasinya jalan, kok pas Naik ke Server Linux Web nya Error Cacat??\" <b>Vagrant membungkam pembelaan itu</b>. Ia menghadirkan Mesin Virtual CLI Linux (Box) di balik layar persis yg sama ke laptop semua orang yang mengetik argumen vagrant yang sama.</p>\n<h3>2. Persiapan Amunisi Lokal</h3>\n<p>Install aplikasi VirtualBox (Sebagai Engine Hipervisor di latar belakang). Lalu install Aplikasi Vagrant for Windows.</p>\n<h3>3. Deklarasi OS di Windows Terminal (Powershell/CMD)</h3>\n<pre><code class=\"language-powershell\"># Buka Folder Project baru bernama (TestingOS) , masuk kedalamnya\ncd TestingOS\n\n# Memecut penciptaan file deklarasi OS bernama Vagrantfile yang minta citra 'bento/ubuntu-20.04' secara resmi\nvagrant init bento/ubuntu-20.04</code></pre>\n<h3>4. Booting OS (Magis!)</h3>\n<pre><code class=\"language-powershell\"># Akan memakan waktu lumayan lama saat download pertama citra ghaib\nvagrant up\n\n# Saat OS ubuntu nya sdh running jalan santai di virtual box tersembunyi\n# KITA MASUK DAN REMOTE MELALUI SSH ROOT OTOMATIS!\nvagrant ssh</code></pre>\n<p>Pusing Linuxnya dah berantakan anda obok-obok praktek instalasi paket? Ketik  di Powershell: <code>vagrant destroy</code> lalu <code>vagrant up</code>. Mesin itu dihancurkan ke debu dan diciptakan baru secara suci dalam hitungan DETIK. Ngeri kan?</p>",
                'level_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Memblokir Situs Dinamis: Squid Proxy Transparent & MikroTik',
                'slug' => Str::slug('Squid Proxy Transparent MikroTik Integrasi'),
                'category' => 'Security',
                'author' => 'Security Analyst',
                'read_time' => 7,
                'excerpt' => 'Cegah Karyawan nakal main Reddit atau Game Online. Sambungkan Layer 7 HTTP Squid Proxy pada Linux menuju MikroTik NAT-Redirection Otomatis.',
                'content' => "<h3>1. Arsitektur Terpisah</h3>\n<p>Router Mikrotik CPU nya lelet untuk memfilter nama domain web secara manual di RAM kecilnya. Kita suruh debian menyalakan paket (Squid) via terminal port 3128. Lalu Trafik Lan Port 80 mikrotik kita belokan ke Port Squid si Linux!</p>\n<h3>2. Instalasi dan Setup Dasar Squid Proxy</h3>\n<pre><code class=\"language-bash\">apt install squid -y\n\n# Ubah file sakral /etc/squid/squid.conf\nhttp_port 3128 transparent # Penting!! Keyword Transparent berarti membiarkan mikrotik yg nge-forward tanpa client sadari ada proxy di tengahnya!\n\n# Menciptakan Database Kata/Website Terlarang ACL (Access Control List)\nacl BlokirSitus dstdomain .reddit.com .facebook.com .judionline.com\nacl BlokirKata url_regex -i porn sex judi\n\n# DENY (Tolak dan lempar Error layar HTML Merah di browser tujuann!)\nhttp_access deny BlokirSitus\nhttp_access deny BlokirKata\n# Tetap izinkan sisa internet lainnya (Kalau tidak Web apapun gagal tembus)!\nhttp_access allow all</code></pre>\n<h3>3. Redirect Mikrotik Mangle/NAT (Suntik di RouterOS Gateway)</h3>\n<p>Anggap router Mikrotik adalah IP X. IP Lokal Squid PC adalah 192.168.88.254.</p>\n<pre><code class=\"language-bash\">/ip firewall nat\n# -p TCP 80 = Apabila ada Trafik HTTP jalan-jalan dari client LAN..\n# action dst-nat = Giring secara Paksa tujuannya (Destination) disuntik masuk lubang cacing Squid!!\nadd chain=dstnat protocol=tcp dst-port=80 action=dst-nat to-addresses=192.168.88.254 to-ports=3128</code></pre>\n<p>Tanpa Client sadari perlu Setting Internet Proxy Options di Browser laptop dia.. Tiba-tiba Facebooknya keblok!! Hahaha (Di era Modern, Teknik Ini agak mandul pada HTTPS Port 443 krna Sertifikat TLS).</p>",
                'level_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Manajemen Access Point Massal: MikroTik CAPsMAN',
                'slug' => Str::slug('Manajemen Access Point MikroTik CAPsMAN'),
                'category' => 'Networking',
                'author' => 'Wireless Network Engineer',
                'read_time' => 5,
                'excerpt' => 'Mengatur 1.000 WiFi Access Point di Hotel dari 1 Menu Saja. Memanfaatkan Controlled Access Point system Manager Mikrotik tanpa Pusing Remote 1-1.',
                'content' => "<h3>1. Mengganti Mikrotik Anda menjadi WiFi Dumb-Node (CAP)</h3>\n<p>CAPsMAN bekerja persis sperti Controller di gedung kampus. Mikrotik pemancar (Pemancar Lantai 1, Lantai 2) dibuat BODOH (Hanya menangkap perintah dari 1 Router Utama Kepala/Manager).</p>\n<h3>2. Konfigurasi Pada Controller Utama/Sang Manajer (CAPsMAN Server)</h3>\n<pre><code class=\"language-bash\"># 1. Menghidupkan Radar Sinyal Manager Utama (Aktif!)\n/caps-man manager set enabled=yes\n\n# 2. Membuat Resep/Profile Spesifikasi Konfigurasi Wifi (Nama, Sandinya..)\n/caps-man configuration\nadd name=SSID-GedungA ssid=\"Kampus_Jeblos_Gedung_A\" security=ProfileSandiKu datapath.bridge=bridge-lokal-wifi mode=ap\n\n# 3. Membuat Provisioning (Jika ada AP bodoh nancap ke saya,, Tolong berikan konfigurasi SSID Kampus Gedung A diatas ke dalam otak dia secara otomatis paksa!)\n/caps-man provisioning\nadd action=create-dynamic-enabled master-configuration=SSID-GedungA</code></pre>\n<h3>3. Konfigurasi Pada Router WiFi Pelabuhan/Budak (CAP)</h3>\n<pre><code class=\"language-bash\"># Suruh si WiFi Murahan milik lantai 2 ini, buang otak Wifi aslinya, nunduk jadi CAP bawahan. Dan Minta petunjuk dari IP Controller 10.10.10.1 di Ruang Server Base Lantai Bawah!\n/interface wireless cap\nset enabled=yes interfaces=wlan1 discovery-interfaces=ether1_uplink_lokal caps-man-addresses=10.10.10.1</code></pre>\n<p>Setelah di reboot, Antarmuka Menu Wireles wlan1 di AP Bawahan/Budak langsung hilang dikuasai/di-lock Tulisan Merah dari CAPsMAN Induk. Canggih Banget sumpah!</p>",
                'level_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pengamanan Enkripsi Harddisk Kelas Keras (LUKS Linux)',
                'slug' => Str::slug('Linux Unified Key Setup LUKS Disk Encryption'),
                'category' => 'Security',
                'author' => 'Security Hardening',
                'read_time' => 7,
                'excerpt' => 'Bagaimana jika maling fisik mencabut Harddisk Data Nasabah dan mencolooknya di Komputer dia? Amankan Storage pakai sandi militer terenkripsi di level Block!',
                'content' => "<h3>1. Bukan Proteksi Sandi Bios, Ini Proteksi Block Binary!</h3>\n<p>File Zip yg dikasih sandi itu lambat dan rentan brute-force softwarenya. Kita mau seluruh Volume (Partisi Utuhnya /dev/sdb1) yang dikunci. Program di Linux untuk memfalitasi ini dan mem-Mounting decryptions secara real time on-the-fly adalah <b>Cryptsetup (LUKS Header)</b>.</p>\n<h3>2. Proses Format Menjadi Piringan Kripto</h3>\n<pre><code class=\"language-bash\"># Ingat, Pastikan Partisi Baru (Umpamanya sdb1 khusus Data base rahasia) bener-bener gak ada isi datanya, krna bakal di lumat.\napt install cryptsetup -y\n\n# Ubah sdb1 menjadi mesin giling cyrptografis LUKS, kamu wajib isikan Password MASTER Disini! Password ini tak prnah bisa di reset walo pakai Tuhan Root LInux skalipun!\ncryptsetup luksFormat /dev/sdb1</code></pre>\n<h3>3. Membuka (Un-Lock) Dan Melapisi Disk Giling Tadi</h3>\n<p>Setelah Disk Jadi \"Blok Hitam\". Kamu wajib membongkarnya sebagai nama sementra `/dev/mapper/namabebas` dlu untuk memakainya!</p>\n<pre><code class=\"language-bash\"># Buka gemboknya (LUMEN_SECRET adalah nama mapper pintu virtual bukaan lu)\ncryptsetup luksOpen /dev/sdb1 LUMEN_SECRET\n\n# Setelah di mapping, di balik bayangan, partisi lu sekarang ada di map /dev/mapper/LUMEN_SECRET !\n# Format Ext4 dong seperti biasa sblm dipakai !!\nmkfs.ext4 /dev/mapper/LUMEN_SECRET\n\n# Terakhir, Mount masuk ke OS debian buat dipake nyimpen file database rahasia!\nmount /dev/mapper/LUMEN_SECRET /var/lib/mysql_secure</code></pre>\n<h3>4. Mencopot USB FlasHdisk Gembok</h3>\n<p>Sangat dianjurkan stelah selesei nyimpen, umount disk mapper nya lalu KUNCI DIRINYA sndiri Rapat-rapat pake sintax luksClose biar maling kebingungan!</p>",
                'level_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('articles')->insert($articles);
    }
}
